Signpost energy library updates
lab11/signpost-software pull request #14
Opened 2017-06-07 03:26 UTC by adkinsjd

Update the energy monitor library. Not ready to merge (I'll push some more stylistic fixes), but I wanted to get it in and start high level review.

Summary of changes:
 - rename signpost_energy to signpost_energy_monitors (this is to differentiate between upcoming signpost_energy_policy libraries)
   - also remove signpost_energy.h include from apps that don't use it
   - unfortunately it seems that changes didn't get tracked across rename :disappointed: 
 - A near rewrite of the signpost_energy(_monitors) library. 
    - More consistent naming of functions
    - units removed from names of functions
    - all conversions pushed into drivers
    - return types that better match reality
 - Apps are all updated to take advantages of these changes

2017-06-07 17:36 UTC, ppannuto requested changes
Only looked over libsignpost so far, none of the apps

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +void signpost_energy_init_ltc2941 (void) {
I think there should still just be `signpost_energy_init` exposed to apps. We have the ID chip on boards for a reason, the library should handle choosing the right energy monitor for you

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +/////////////////////////////////////////////////////////
nit: missing spaces between `//Initialization` (and next line)

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +    //max17205_configure_pack_sync();
?

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +// ////////////////////////////////////////////
nit: one missing `/`

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +// ////////////////////////////////////////////////
`/`

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +uint32_t signpost_energy_get_controller_energy (void) {
Why does this not have a unit attached to it any more? The interior function has `uah`, but we're hiding that from the caller? I very consciously put units on every function when I wrote this the first time, it's makes it way more usable
(edit: all of these need units)

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +uint32_t signpost_energy_get_controller_current (void) {
Units here too

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +    return (int)c;
return cast doesn't match return type

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +//More information about the battery
nit: missing space

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +uint32_t signpost_energy_get_battery_capacity (void) {
unit
(and below)

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +// ///////////////////////////////////////////////////////////////////
`/`

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +uint16_t signpost_energy_get_battery_voltage (void) {
units here too

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.h
> +//in Mohm
style: missing spaces on a bunch of these comments

2017-06-07 17:36 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.h
> +#define POWER_MODULE_SOLAR_RSENSE 50
Why bury the unit in a comment here? `POWER_MODULE_RSENSE_MOHM`?

2017-06-07 17:38 UTC, adkinsjd commented on apps/libsignpost/signpost_energy_monitors.c
> +void signpost_energy_init_ltc2941 (void) {
I totally agree, we just don't have anything working to do that right now

2017-06-07 17:38 UTC, adkinsjd commented on apps/libsignpost/signpost_energy_monitors.c
> +void signpost_energy_init_ltc2941 (void) {
There needs to be an i2c eeprom driver written - which feels like something that should go in another PR

2017-06-07 17:38 UTC, adkinsjd commented on apps/libsignpost/signpost_energy_monitors.c
> +    //max17205_configure_pack_sync();
What are you questioning? The configure pack? I should remove that - it no longer exists.

2017-06-07 17:40 UTC, adkinsjd commented on apps/libsignpost/signpost_energy_monitors.c
> +uint32_t signpost_energy_get_controller_energy (void) {
I explicitly removed units, and instead decided to pick units for the whole library (see my summary comments). We can add them back - I don't care that much - but I just thought if they were all the same we didn't need to put the unit name.

There are comments with units in the header.

2017-06-07 17:41 UTC, adkinsjd commented on apps/libsignpost/signpost_energy_monitors.h
> +#define POWER_MODULE_SOLAR_RSENSE 50
Yeah that's a good fix

2017-06-07 17:42 UTC, adkinsjd commented
Per my first comment I hadn't done any stylistic passes on this yet so yall don't need to make that effort yet unless you just want to. I appreciate the help, but it feels like a waste of your time until I put at least a little effort into style.

2017-06-07 17:51 UTC, ppannuto commented on apps/libsignpost/signpost_energy_monitors.c
> +uint32_t signpost_energy_get_controller_energy (void) {
In one case the unit is with the function where it's used every place it's used automatically. In the other case I have to go look up a comment in a header file to see what unit I'm getting back. Having the unit with the code really helps readability

2017-06-07 17:52 UTC, ppannuto commented
Missed the parenthetical on style, but I didn't spend too much time thinking about that, just highlighting when I saw them

2017-06-07 19:04 UTC, adkinsjd commented
Pat all of your changes have been addressed except automatic configuration (which as discussed should go in another pr after eeprom driver is done)

2017-06-08 19:43 UTC, ppannuto approved these changes
There are several style nits still, but there's a PR working through Tock that will just fix all of those automatically, so not worth fixing here.

I think this is gtg

2017-06-08 19:44 UTC, merged