move microwave radar code into library
lab11/signpost-software pull request #23
Opened 2017-07-24 05:17 UTC by adkinsjd

This is part of the effort to abstract functionality of a device (i.e. how the microwave radar works) from the application itself (sending data on the radio, energy adaptivity).

It also makes changes in the way motion is detected. Rather than looking for a threshold it does a sliding window integration (integral [0-window] abs(sample-zero_motion_sample)). With a larger amplification on the hardware, this seems to be working reliably. It can detect motion of just waving from across the room with no false positives.

2017-07-24 19:05 UTC, brghena requested changes

2017-07-24 19:05 UTC, brghena commented on apps/microwave_radar_module/sense_speed_send_bytes/main.c
>      // set to about two seconds, but a larger prime number so that hopefully we
Fix the comment

2017-07-24 19:05 UTC, brghena commented on apps/libsignpost/microwave_radar.c
> +    return -1;
Return `TOCK_ENOSUPPORT` instead

2017-07-24 19:05 UTC, brghena commented on apps/libsignpost/microwave_radar.c
> +#define SAMPLE_FREQ 4000
Why 4 kHz? Some comment here explaining the choice would be great.

2017-08-02 18:20 UTC, adkinsjd commented
Okay Branden these changes should be integrated.

2017-08-08 16:14 UTC, brghena approved these changes

2017-08-08 16:14 UTC, merged